# Generated by Django 2.1.3 on 2018-11-27 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='actived',
            field=models.BooleanField(default=False),
        ),
    ]
