# Generated by Django 2.1.3 on 2018-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0002_rent_actived'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='actived',
        ),
        migrations.AddField(
            model_name='product',
            name='actived',
            field=models.BooleanField(default=False),
        ),
    ]
