# Generated by Django 2.1.3 on 2018-11-27 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0003_auto_20181127_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='actived',
        ),
    ]
