# Generated by Django 2.1.3 on 2018-11-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentapp', '0004_remove_product_actived'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='actived',
            field=models.BooleanField(default=False),
        ),
    ]
